apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  namespace: external-secrets
  labels:
    app: external-secrets
    component: auth
type: Opaque
stringData:
  access-key-id: test
  secret-access-key: test
