apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: app-credentials-sync
  namespace: default
  labels:
    app: rideshare-platform
    component: external-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: localstack-secrets
    kind: SecretStore
  target:
    name: app-credentials
    creationPolicy: Owner
  data:
    - secretKey: REDIS_PASSWORD
      remoteRef:
        key: rideshare/redis
        property: REDIS_PASSWORD
    - secretKey: MINIO_ROOT_USER
      remoteRef:
        key: rideshare/minio
        property: MINIO_ROOT_USER
    - secretKey: MINIO_ROOT_PASSWORD
      remoteRef:
        key: rideshare/minio
        property: MINIO_ROOT_PASSWORD
    - secretKey: MINIO_ACCESS_KEY
      remoteRef:
        key: rideshare/minio
        property: MINIO_ROOT_USER
    - secretKey: MINIO_SECRET_KEY
      remoteRef:
        key: rideshare/minio
        property: MINIO_ROOT_PASSWORD
    - secretKey: AIRFLOW_POSTGRES_PASSWORD
      remoteRef:
        key: rideshare/postgres-airflow
        property: POSTGRES_PASSWORD
    - secretKey: POSTGRES_METASTORE_PASSWORD
      remoteRef:
        key: rideshare/postgres-metastore
        property: POSTGRES_PASSWORD
    - secretKey: KAFKA_SASL_USERNAME
      remoteRef:
        key: rideshare/kafka
        property: KAFKA_SASL_USERNAME
    - secretKey: KAFKA_SASL_PASSWORD
      remoteRef:
        key: rideshare/kafka
        property: KAFKA_SASL_PASSWORD
