# Production patch: Override BRONZE_BUCKET for bronze-init CronJob
# Replace <account-id> with AWS account ID during deploy (handled by deploy.yml sed)
apiVersion: batch/v1
kind: CronJob
metadata:
  name: bronze-init
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: bronze-init
              env:
                - name: BRONZE_BUCKET
                  value: "rideshare-<account-id>-bronze"
